# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.0.0

pipelines:
  branches:
    master:
       - step:
           caches:
              - node
           deployment: production
           script:
              - npm install
              - npm install gulp karma-cli -g
              - gulp --production
              - npm test
              - gulp deploy --AWS_S3_KEY=$AWS_ACCESS_KEY_ID --AWS_S3_SECRET=$AWS_SECRET_ACCESS_KEY --REGION=$REGION --BUCKET=$BUCKET